### ISSUE TITLE
Cannot deserialize Facility - it is impossible to safely provision or query a device

### ISSUE THREAD

**Issue by m10f** [packethost/packet-java#2]
After calling create_device I get the below stack trace - though it does create a device.  Apparently the code for Facility has a String for Address, while the API docs say suggest that it is a more complex object.  Consequently, it seems any attempt to deserialize a Facility throws an exception.

`java.util.concurrent.ExecutionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1152 path $.facility.address
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at Main.main(Main.java:34)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1152 path $.facility.address
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)`

**Comment by jeevatkm** [comment]
@m10f  When I created this library, [facility address was type](https://github.com/packethost/packet-java/blob/master/src/main/java/net/packet/pojo/Facility.java#L26) `String`. My best guess is payload structure might have changed now to custom Object type. 

Could you please post the current payload structure you're receiving? Also you could submit PR fo this change.

**Comment by displague** [comment]
Just as the successor to Facilities scoping is Metro scoping for Equinix Metal device management, the successor to packet-java is metal-java. You can find the project here with several examples that demonstrate that this issue has been resolved in the new bindings: https://github.com/equinix-labs/metal-java/blob/main/examples/

This is the last open issue on this project. I'm closing it to go along with #11.

@m10f, if you are still using Metal with Java, please give the new project a look.  It is generated from the OpenAPIv3 API Spec for Equinix Metal and is in use by other developers.
